# Generated by Django 4.2.11 on 2026-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0005_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion_imagenes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solucion_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
