# Generated by Django 4.2.11 on 2026-03-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0008_add_nombre_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cerrador',
                'verbose_name_plural': 'Cerradores',
                'db_table': 'cerrador',
            },
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={},
        ),
        migrations.AlterModelTable(
            name='motivo',
            table=None,
        ),
        migrations.AddField(
            model_name='ticket',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to='ticket_system.cerrador'),
        ),
    ]
