# Generated by Django 4.2.11 on 2026-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0009_cerrador_alter_motivo_options_alter_motivo_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivo',
            options={'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AlterModelTable(
            name='motivo',
            table='motivo',
        ),
    ]
